api_platform:
  title: Steamish v3
  version: 0.0.1
  show_webby: false
  use_symfony_listeners: true

  swagger:
    swagger_ui_extra_configuration:
      docExpansion: none # list|full|none
    api_keys:
      JWT:
        name: Authorization
        type: header

  defaults:
    stateless: false
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]